# Generated by Django 3.0.4 on 2020-06-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegalCode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApportNatureFichiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContratApportNature', models.BooleanField(verbose_name="Contrat d'apport en nature")),
                ('DecisionAssocieApport', models.BooleanField(verbose_name='Décision associé(Apport)')),
                ('DecisionAssocieDesignationCommissaire', models.BooleanField(verbose_name='Décision associé(Désignation commissaire)')),
                ('RapportduPresident', models.BooleanField(verbose_name='Rapport du Président')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Associe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sexe_Associe', models.CharField(max_length=4, verbose_name='Sexe')),
                ('Nom_Associe', models.CharField(max_length=4, verbose_name='Nom')),
                ('DateNaissance_Associe', models.DateField(verbose_name='Date de Naissance (dd/mm/yyyy)')),
                ('Partie_Associe', models.CharField(max_length=50, verbose_name='Partie')),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristiquesApportNature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_CaracteristiquesApportNature_TotalApportNumeraire', models.FloatField(verbose_name='Apport numéraire total')),
                ('Form_CaracteristiquesApportNature_MontantAugmentationCapital', models.FloatField(verbose_name='Montant augmentation capital')),
            ],
        ),
        migrations.CreateModel(
            name='CommissaireComptes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sexe_CommissaireComptes', models.CharField(max_length=4, verbose_name='Sexe')),
                ('Nom_CommissaireComptes', models.CharField(max_length=40, verbose_name='Nom')),
                ('Partie_CommissaireComptes', models.CharField(max_length=50, verbose_name='Partie')),
            ],
        ),
        migrations.CreateModel(
            name='SocieteBeneficiaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_SocieteBeneficiaire_Nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('Form_SocieteBeneficiaire_Partie', models.CharField(max_length=30, verbose_name='Partie')),
            ],
        ),
        migrations.CreateModel(
            name='SocieteSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_SocieteSource_NomSociete', models.CharField(max_length=50, verbose_name='Nom')),
                ('Form_SocieteSource_FormeJuridique', models.CharField(max_length=50, verbose_name='Forme Juridique')),
                ('Form_SocieteSource_MontantCapital', models.FloatField(verbose_name='Montant Capital')),
                ('Form_SocieteSource_DeviseCapital', models.CharField(max_length=50, verbose_name='Devise Capital')),
                ('Form_SocieteSource_Adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('Form_SocieteSource_ValeurAction', models.FloatField(max_length=100, verbose_name='Valeur Action')),
                ('Form_SocieteSource_Partie', models.CharField(max_length=30, verbose_name='Partie')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
